from __future__ import annotations

import argparse
import ast
import json
import keyword
import re
import sys
from dataclasses import dataclass, field
from functools import partial
from pathlib import Path
from typing import TYPE_CHECKING, Any
from urllib.parse import unquote

import httpx2
from datamodel_code_generator import InputFileType
from datamodel_code_generator import generate as generate_models
from jinja2 import Environment, FileSystemLoader, StrictUndefined, select_autoescape
from pydantic import BaseModel, ValidationError

from .client import APIClient

if TYPE_CHECKING:
    from collections.abc import Mapping, MutableMapping, Sequence

__all__ = ["main"]

_SCHEMA_REF = "#/components/schemas/"
_PRIMITIVES = {"string": "str", "integer": "int", "number": "float", "boolean": "bool"}
_SIMPLE_TYPES = frozenset({None, "array", "object", *_PRIMITIVES})
_OBJECT_KEYS = frozenset(
    {"additionalProperties", "allOf", "anyOf", "oneOf", "properties"}
)
_COMPOSITE_KEYS = _OBJECT_KEYS | {"const", "enum", "not"}
_OPERATION_KEYS = (
    "get",
    "put",
    "post",
    "delete",
    "options",
    "head",
    "patch",
    "trace",
    "query",
)
_METHODS = frozenset({"delete", "get", "head", "options", "patch", "post", "put"})
_BODY_METHODS = frozenset({"patch", "post", "put"})
_SSE_METHODS = frozenset({"get", "post"})
_PARAM_MARKERS = {"cookie": "Cookie", "header": "Header", "query": "Query"}
_JSON_TYPES = frozenset({"*/*", "application/json"})
_FORM_TYPES = ("application/x-www-form-urlencoded", "multipart/form-data")
_EVENT_STREAM = "text/event-stream"
_TEMPLATE = "template.jinja2"
_HEADER = "# Generated by httpxic from an OpenAPI spec."
_MODEL_DEFAULTS: Mapping[str, Any] = {
    "output_model_type": "pydantic_v2.BaseModel",
    "target_python_version": "3.10",
    "use_annotated": False,
    "field_constraints": True,
    "use_union_operator": True,
    "use_double_quotes": True,
    "use_generic_base_class": True,
    "allow_population_by_field_name": True,
    "formatters": ["builtin"],
    "disable_timestamp": True,
    "custom_file_header": _HEADER,
}
_MODEL_RESERVED = frozenset({"input_file_type", "output"})
_CONFIG_KEYS = frozenset(
    {"spec", "output", "class_name", "base_model", "model_options", "filters"}
)
_REQUIRED_CONFIG_KEYS = ("spec", "output")
_URL_PREFIXES = ("http://", "https://")
_IMPORTS = {
    "collections.abc": ("Iterator",),
    "typing": ("Annotated", "Any"),
    "httpx2": ("Response",),
    "httpxic": (
        "APIClient",
        "Body",
        "ClientT",
        "Cookie",
        "File",
        "Form",
        "Header",
        "Query",
        "ServerSentEvent",
        "delete",
        "get",
        "head",
        "options",
        "patch",
        "post",
        "put",
        "sse",
    ),
    "httpxic.filters": (
        "BaseFilter",
        "CursorPaginationFilter",
        "FieldsFilter",
        "Filter",
        "IncludeFilter",
        "OffsetLimitFilter",
        "OrderingFilter",
        "PaginationFilter",
        "SearchFilter",
    ),
    "pydantic": ("Field",),
}
_STDLIB = frozenset({"collections.abc", "typing"})
_PAGINATION_MIXINS = (
    ("PaginationFilter", frozenset({"page", "page_size"})),
    ("CursorPaginationFilter", frozenset({"cursor", "page_size"})),
    ("OffsetLimitFilter", frozenset({"offset", "limit"})),
)
_MIXINS = (
    ("OrderingFilter", frozenset({"sort"})),
    ("SearchFilter", frozenset({"q"})),
    ("FieldsFilter", frozenset({"fields"})),
    ("IncludeFilter", frozenset({"include"})),
)
_FILTER_BASES = [
    "PaginationFilter",
    "OrderingFilter",
    "SearchFilter",
    "FieldsFilter",
    "IncludeFilter",
]
_MIXIN_FIELDS = {"q": "query"}
_RESERVED_FIELDS = frozenset(dir(BaseModel))
_NULL_SCHEMA: Mapping[str, Any] = {"type": "null"}
_RESERVED_MODELS = frozenset(
    {name for names in _IMPORTS.values() for name in names}
    | {"AnyUrl", "AwareDatetime", "BaseModel", "ConfigDict", "Decimal", "Enum"}
    | {"Field", "Literal", "RootModel", "UUID"}
)
_RESERVED_METHODS = frozenset(
    {name for name in dir(APIClient) if not name.startswith("__")}
    | {"decode_options", "http", "is_async", "raise_for_status"}
    | {name for name in _IMPORTS["httpxic"] if name.islower()}
)


class _Unsupported(Exception):
    """An operation the generator cannot express, skipped with this reason."""


def _words(text: str) -> list[str]:
    spaced = re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", " ", text)
    return re.findall(r"[A-Za-z0-9]+", spaced)


def _snake(text: str) -> str:
    name = "_".join(_words(text)).lower()
    return name if name[:1].isalpha() else f"_{name}"


def _pascal(text: str) -> str:
    name = "".join(word[:1].upper() + word[1:] for word in _words(text))
    return name if name[:1].isalpha() else f"Model{name}"


def _unique(name: str, taken: set[str], separator: str = "_") -> str:
    base = f"{name}_" if keyword.iskeyword(name) else name
    candidate, index = base, 1
    while candidate in taken:
        index += 1
        candidate = f"{base}{separator}{index}"
    taken.add(candidate)
    return candidate


def _unescape(part: str) -> str:
    return unquote(part).replace("~1", "/").replace("~0", "~")


def _rewrite_refs(node: Any, renames: Mapping[str, str]) -> None:
    if isinstance(node, list):
        for child in node:
            _rewrite_refs(child, renames)
    elif isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str) and ref.startswith(_SCHEMA_REF):
            name, separator, rest = ref.removeprefix(_SCHEMA_REF).partition("/")
            renamed = renames.get(_unescape(name), name)
            node["$ref"] = f"{_SCHEMA_REF}{renamed}{separator}{rest}"
        for child in node.values():
            _rewrite_refs(child, renames)


def _schema_type(schema: Mapping[str, Any]) -> tuple[str | None, bool]:
    kind = schema.get("type")
    if isinstance(kind, list):
        rest = [item for item in kind if item != "null"]
        return (rest[0] if len(rest) == 1 else "union"), "null" in kind
    return kind, schema.get("nullable") is True


def _media(content: Mapping[str, Any]) -> dict[str, Any]:
    return {key.split(";")[0].strip().lower(): value for key, value in content.items()}


def _json_type(media: Mapping[str, Any]) -> str | None:
    return next(
        (key for key in media if key in _JSON_TYPES or key.endswith("+json")), None
    )


def _nullable(schema: Mapping[str, Any]) -> tuple[Mapping[str, Any], bool]:
    """Unwrap ``anyOf``/``oneOf: [<schema>, {type: null}]`` into ``<schema>``."""
    for key in ("anyOf", "oneOf"):
        variants = schema.get(key)
        if isinstance(variants, list) and _NULL_SCHEMA in variants:
            rest = [variant for variant in variants if variant != _NULL_SCHEMA]
            if len(rest) == 1:
                return rest[0], True
    return schema, False


def _filter_bases(optional: set[str]) -> tuple[list[str], set[str]]:
    """Pick the ``httpxic.filters`` mixins whose parameters are all present."""
    pagination = next(
        ((name, wires) for name, wires in _PAGINATION_MIXINS if wires <= optional),
        None,
    )
    matched = [
        *([pagination] if pagination else []),
        *((name, wires) for name, wires in _MIXINS if wires <= optional),
    ]
    bases = [name for name, _ in matched]
    consumed = {wire for _, wires in matched for wire in wires}
    return (["Filter"] if bases == _FILTER_BASES else bases), consumed


def _check_locations(params: Sequence[Mapping[str, Any]]) -> None:
    for param in params:
        location = param["in"]
        if location != "path" and (
            location not in _PARAM_MARKERS or param.get("style") == "deepObject"
        ):
            msg = f"{param.get('style', location)!r} parameter {param['name']!r}"
            raise _Unsupported(msg)


@dataclass(slots=True)
class _Param:
    name: str
    annotation: str
    marker: str | None = None
    options: dict[str, str] = field(default_factory=dict)
    required: bool = True


@dataclass(slots=True)
class _Signature:
    names: set[str] = field(default_factory=partial(set, ["self"]))
    positional: list[_Param] = field(default_factory=list)
    required: list[_Param] = field(default_factory=list)
    optional: list[_Param] = field(default_factory=list)

    def add(self, param: _Param) -> None:
        (self.required if param.required else self.optional).append(param)


@dataclass(slots=True)
class _FilterModel:
    name: str
    bases: list[str]
    fields: list[_Param]

    @property
    def required(self) -> bool:
        return any(param.required for param in self.fields)


@dataclass(slots=True)
class _Operation:
    name: str
    decorator: str
    path: str
    options: dict[str, Any]
    positional: list[_Param]
    keyword: list[_Param]
    returns: str
    filter: _FilterModel | None = None


@dataclass(slots=True)
class _Skipped:
    label: str
    reason: str


class _Generator:
    def __init__(
        self, spec: MutableMapping[str, Any], class_name: str, *, filters: bool
    ) -> None:
        self.spec = spec
        self.filters = filters
        self.model_names = {*_RESERVED_MODELS, class_name}
        self.method_names = set(_RESERVED_METHODS)
        self.used: set[str] = {"APIClient", "ClientT"}
        components = spec.setdefault("components", {})
        schemas = components.get("schemas", {})
        renames = {
            name: _unique(_pascal(name), self.model_names, "") for name in schemas
        }
        self.schemas: dict[str, Any] = {renames[n]: s for n, s in schemas.items()}
        components["schemas"] = self.schemas
        _rewrite_refs(spec, renames)

    def client_module(self, class_name: str) -> str:
        operations = [
            self._render(path, method, item)
            for path, item in self.spec.get("paths", {}).items()
            for method in _OPERATION_KEYS
            if method in item
        ]
        imports = [
            (module, sorted(self.used.intersection(names)))
            for module, names in _IMPORTS.items()
            if self.used.intersection(names)
        ]
        models = sorted(self.used_models())
        groups = (
            [entry for entry in imports if entry[0] in _STDLIB],
            [entry for entry in imports if entry[0] not in _STDLIB],
            [(".models", models)] if models else [],
        )
        return _render_template(
            header=_HEADER,
            class_name=class_name,
            import_groups=[group for group in groups if group],
            filters=[
                op.filter
                for op in operations
                if isinstance(op, _Operation) and op.filter is not None
            ],
            operations=operations,
        )

    def used_models(self) -> set[str]:
        return self.used & self.schemas.keys()

    def _render(
        self, path: str, method: str, item: Mapping[str, Any]
    ) -> _Operation | _Skipped:
        outer, self.used = self.used, set()
        try:
            operation: _Operation | _Skipped = self._method(path, method, item)
        except _Unsupported as exc:
            label = str(item[method].get("operationId") or f"{method.upper()} {path}")
            sys.stderr.write(f"warning: skipped {label!r}: {exc}\n")
            operation = _Skipped(label, str(exc))
        else:
            outer |= self.used
        self.used = outer
        return operation

    def _method(self, path: str, method: str, item: Mapping[str, Any]) -> _Operation:
        if method not in _METHODS:
            msg = f"{method.upper()} operations are not supported"
            raise _Unsupported(msg)
        operation = item[method]
        base = _snake(str(operation.get("operationId") or f"{method}_{path}"))
        hint = _pascal(base)
        signature = _Signature()
        params = self._parameters(item, operation)
        url = self._path_params(path, params, hint, signature)
        filter_model = self._other_params(params, hint, signature)
        body_options = self._body(operation, method, hint, signature)
        returns, stream = self._returns(operation, hint)
        decorator, stream_options = self._decorator(method, stream=stream)
        keyword_only = [*signature.required, *signature.optional]
        if keyword_only:
            self.used.add("Annotated")
        return _Operation(
            name=_unique(base, self.method_names),
            decorator=decorator,
            path=url,
            options={**stream_options, **body_options},
            positional=signature.positional,
            keyword=keyword_only,
            returns=returns,
            filter=filter_model,
        )

    def _parameters(
        self, item: Mapping[str, Any], operation: Mapping[str, Any]
    ) -> list[Mapping[str, Any]]:
        merged: dict[tuple[str, str], Mapping[str, Any]] = {}
        for raw in [*item.get("parameters", []), *operation.get("parameters", [])]:
            param = self._resolve(raw)
            merged[param["name"], param["in"]] = param
        return list(merged.values())

    def _path_params(
        self,
        path: str,
        params: Sequence[Mapping[str, Any]],
        hint: str,
        signature: _Signature,
    ) -> str:
        declared = {p["name"]: p for p in params if p["in"] == "path"}

        def placeholder(match: re.Match[str]) -> str:
            wire = match.group(1)
            name = _unique(_snake(wire), signature.names)
            schema = declared.get(wire, {}).get("schema", {"type": "string"})
            annotation = self._scalar(schema, hint + _pascal(wire), wire)
            signature.positional.append(_Param(name, annotation))
            return f"{{{name}}}"

        return re.sub(r"\{([^{}]*)\}", placeholder, path)

    def _other_params(
        self, params: Sequence[Mapping[str, Any]], hint: str, signature: _Signature
    ) -> _FilterModel | None:
        _check_locations(params)
        query = [param for param in params if param["in"] == "query"]
        filter_model = self._filter_model(query, hint) if self.filters else None
        for param in params:
            wire, location = param["name"], param["in"]
            if location == "path" or (filter_model and location == "query"):
                continue
            name = _unique(_snake(wire), signature.names)
            annotation = self._scalar(
                param.get("schema", {}), hint + _pascal(wire), wire
            )
            signature.add(
                _Param(
                    name,
                    annotation,
                    self._use(_PARAM_MARKERS[location]),
                    options={} if name == wire else {"alias": wire},
                    required=param.get("required") is True,
                )
            )
        if filter_model is not None:
            signature.add(
                _Param(
                    _unique("filters", signature.names),
                    filter_model.name,
                    self._use("Query"),
                    required=filter_model.required,
                )
            )
        return filter_model

    def _filter_model(
        self, query: Sequence[Mapping[str, Any]], hint: str
    ) -> _FilterModel | None:
        optional = {p["name"] for p in query if p.get("required") is not True}
        bases, consumed = _filter_bases(optional)
        if not bases and not any("__" in p["name"] for p in query):
            return None
        taken = {*_RESERVED_FIELDS, *(_MIXIN_FIELDS.get(w, w) for w in consumed)}
        fields = []
        for param in query:
            wire = param["name"]
            if wire in consumed:
                continue
            valid = wire.isidentifier() and not wire.startswith("_")
            name = _unique(wire if valid else _snake(wire), taken)
            annotation = self._scalar(
                param.get("schema", {}), hint + _pascal(wire), wire
            )
            if name != wire:
                self._use("Field")
            fields.append(
                _Param(
                    name,
                    annotation,
                    options={} if name == wire else {"alias": wire},
                    required=param.get("required") is True,
                )
            )
        return _FilterModel(
            name=_unique(f"{hint}Filter", self.model_names, ""),
            bases=[self._use(base) for base in bases or ["BaseFilter"]],
            fields=fields,
        )

    def _body(
        self,
        operation: Mapping[str, Any],
        method: str,
        hint: str,
        signature: _Signature,
    ) -> dict[str, Any]:
        if "requestBody" not in operation:
            return {}
        if method not in _BODY_METHODS:
            msg = f"request body on {method.upper()}"
            raise _Unsupported(msg)
        media = _media(self._resolve(operation["requestBody"]).get("content", {}))
        json_type = _json_type(media)
        form_type = next((key for key in _FORM_TYPES if key in media), None)
        if form_type is not None and json_type is None:
            self._form(media[form_type].get("schema", {}), hint, signature)
            return {}
        if not media:
            msg = "request body without content"
            raise _Unsupported(msg)
        content_type = json_type or next(iter(media))
        annotation = (
            "bytes"
            if json_type is None
            else self._annotation(media[json_type].get("schema", {}), f"{hint}Request")
        )
        signature.add(
            _Param(_unique("body", signature.names), annotation, self._use("Body"))
        )
        if content_type in _JSON_TYPES:
            return {}
        return {"headers": {"Content-Type": content_type}}

    def _form(
        self, schema: Mapping[str, Any], hint: str, signature: _Signature
    ) -> None:
        resolved = self._resolve(schema)
        required = set(resolved.get("required", []))
        for prop, prop_schema in resolved.get("properties", {}).items():
            if (
                not prop.isidentifier()
                or keyword.iskeyword(prop)
                or prop in signature.names
            ):
                msg = f"form field {prop!r} is not a valid parameter name"
                raise _Unsupported(msg)
            signature.names.add(prop)
            if self._resolve(prop_schema).get("format") == "binary":
                annotation, marker = "bytes", self._use("File")
            else:
                annotation = self._scalar(prop_schema, hint + _pascal(prop), prop)
                marker = self._use("Form")
            signature.add(_Param(prop, annotation, marker, required=prop in required))

    def _returns(self, operation: Mapping[str, Any], hint: str) -> tuple[str, bool]:
        responses = operation.get("responses", {})
        code = min(
            (code for code in responses if str(code).startswith("2")),
            key=str,
            default=None,
        )
        if code is None:
            return self._use("Response"), False
        media = _media(self._resolve(responses[code]).get("content", {}))
        if _EVENT_STREAM in media:
            event = self._event(media[_EVENT_STREAM], hint)
            return f"{self._use('Iterator')}[{event}]", True
        json_type = _json_type(media)
        if json_type is not None:
            schema = media[json_type].get("schema", {})
            return self._annotation(schema, f"{hint}Response"), False
        return self._use("Response") if media else "None", False

    def _event(self, media: Mapping[str, Any], hint: str) -> str:
        if "itemSchema" in media:
            item = self._resolve(media["itemSchema"])
            data = self._resolve(item.get("properties", {}).get("data", {}))
            schema = data.get("contentSchema")
        else:
            schema = media.get("schema")
        if schema is None or self._resolve(schema).get("type") == "string":
            return self._use("ServerSentEvent")
        return self._annotation(schema, f"{hint}Event")

    def _decorator(self, method: str, *, stream: bool) -> tuple[str, dict[str, Any]]:
        if not stream:
            return self._use(method), {}
        if method not in _SSE_METHODS:
            msg = f"event stream on {method.upper()}"
            raise _Unsupported(msg)
        return self._use("sse"), {"method": "POST"} if method == "post" else {}

    def _scalar(self, schema: Mapping[str, Any], hint: str, label: str) -> str:
        if not self._is_scalar(schema):
            msg = f"non-scalar parameter {label!r}"
            raise _Unsupported(msg)
        return self._annotation(schema, hint)

    def _is_scalar(self, schema: Mapping[str, Any]) -> bool:
        resolved, _ = _nullable(self._resolve(schema))
        resolved = self._resolve(resolved)
        if resolved.get("type") == "array":
            return self._is_scalar(resolved.get("items", {}))
        return resolved.get("type") != "object" and not _OBJECT_KEYS & resolved.keys()

    def _annotation(self, schema: Mapping[str, Any], hint: str) -> str:
        if "$ref" in schema:
            resolved = self._resolve(schema)
            name = str(schema["$ref"]).removeprefix(_SCHEMA_REF)
            if name in self.schemas:
                return self._use(name)
            return self._annotation(resolved, hint)
        inner, nullable = _nullable(schema)
        if nullable:
            return f"{self._annotation(inner, hint)} | None"
        kind, nullable = _schema_type(schema)
        if _COMPOSITE_KEYS & schema.keys() or kind not in _SIMPLE_TYPES:
            return self._hoist(schema, hint)
        if kind == "array":
            base = f"list[{self._annotation(schema.get('items', {}), f'{hint}Item')}]"
        elif kind in _PRIMITIVES:
            base = _PRIMITIVES[kind]
        elif kind == "object":
            base = f"dict[str, {self._use('Any')}]"
        else:
            base = self._use("Any")
        return f"{base} | None" if nullable else base

    def _hoist(self, schema: Mapping[str, Any], hint: str) -> str:
        name = _unique(hint, self.model_names, "")
        self.schemas[name] = schema
        return self._use(name)

    def _use(self, name: str) -> str:
        self.used.add(name)
        return name

    def _resolve(self, node: Mapping[str, Any]) -> Mapping[str, Any]:
        while "$ref" in node:
            node = self._pointer(str(node["$ref"]))
        return node

    def _pointer(self, ref: str) -> Any:
        if not ref.startswith("#/"):
            msg = f"external $ref {ref!r}"
            raise _Unsupported(msg)
        node: Any = self.spec
        try:
            for part in ref[2:].split("/"):
                node = node[_unescape(part)]
        except (KeyError, TypeError) as exc:
            msg = f"unresolvable $ref {ref!r}"
            raise _Unsupported(msg) from exc
        return node


def _literal(value: Any) -> str:
    if isinstance(value, dict):
        items = ", ".join(
            f"{_literal(key)}: {_literal(item)}" for key, item in value.items()
        )
        return f"{{{items}}}"
    text = repr(value)
    if isinstance(value, str) and '"' not in value:
        return f'"{text[1:-1]}"'
    return text


def _render_template(**context: Any) -> str:

    environment = Environment(
        loader=FileSystemLoader(Path(__file__).parent),
        autoescape=select_autoescape(),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    environment.filters["literal"] = _literal
    return environment.get_template(_TEMPLATE).render(**context)


def _read(source: str) -> Any:
    if source.startswith(_URL_PREFIXES):
        text = httpx2.get(source, follow_redirects=True).raise_for_status().text
    else:
        text = Path(source).read_text(encoding="utf-8")
    if text.lstrip().startswith("{"):
        return json.loads(text)
    import yaml  # noqa: PLC0415

    return yaml.safe_load(text)


def _load(source: str) -> MutableMapping[str, Any]:
    spec = _read(source)
    if not isinstance(spec, dict) or not str(spec.get("openapi")).startswith("3."):
        msg = f"{source}: not an OpenAPI 3.x document"
        raise SystemExit(msg)
    return spec


def _write_models(
    target: Path, spec: Mapping[str, Any], options: Mapping[str, Any]
) -> set[str]:
    try:
        generate_models(
            dict(spec),
            **options,
            input_file_type=InputFileType.OpenAPI,
            output=target,
        )
    except ValidationError as exc:
        msg = f"invalid model options: {exc}"
        raise SystemExit(msg) from exc
    tree = ast.parse(target.read_text(encoding="utf-8"))
    return {node.name for node in tree.body if isinstance(node, ast.ClassDef)}


def generate(  # noqa: PLR0913
    source: str,
    output: Path,
    class_name: str | None = None,
    model_options: Mapping[str, Any] | None = None,
    base_model: str | None = None,
    *,
    filters: bool = True,
) -> None:
    """Generate an httpxic client package from an OpenAPI 3.x document.

    ``model_options`` are passed to ``datamodel_code_generator.generate()``
    over httpxic's defaults, e.g. ``{"target_python_version": "3.12"}``.
    ``base_model`` (``"package.module:Class"``) replaces the generated
    ``BaseModel`` that every schema inherits from. With ``filters``, query
    parameters matching ``httpxic.filters`` mixins (or ``field__lookup`` names)
    are bundled into a generated filter class instead of raw parameters.
    """
    model_options = model_options or {}
    reserved = _MODEL_RESERVED & model_options.keys()
    if reserved:
        msg = f"model options {', '.join(sorted(reserved))} are set by httpxic"
        raise SystemExit(msg)
    base_options = {} if base_model is None else _base_model_options(base_model)
    options = {**_MODEL_DEFAULTS, **base_options, **model_options}
    spec = _load(source)
    title = str(spec.get("info", {}).get("title") or "Api")
    class_name = (
        _unique(f"{_pascal(title)}Client", set(_RESERVED_MODELS), "")
        if class_name is None
        else _class_name(class_name)
    )
    generator = _Generator(spec, class_name, filters=filters)
    client = generator.client_module(class_name)
    output.mkdir(parents=True, exist_ok=True)
    if generator.schemas:
        defined = _write_models(output / "models.py", spec, options)
        missing = generator.used_models() - defined
        if missing:
            msg = (
                f"datamodel-code-generator did not emit the models "
                f"{', '.join(sorted(missing))} referenced by the client"
            )
            raise SystemExit(msg)
    (output / "client.py").write_text(client, encoding="utf-8")
    (output / "__init__.py").write_text(
        f'from .client import {class_name}\n\n__all__ = ["{class_name}"]\n',
        encoding="utf-8",
    )


def _config(path: Path) -> dict[str, Any]:
    config = _read(str(path))
    if not isinstance(config, dict):
        msg = f"{path}: config must be a mapping"
        raise SystemExit(msg)
    unknown = config.keys() - _CONFIG_KEYS
    if unknown:
        msg = f"{path}: unknown config keys {', '.join(sorted(unknown))}"
        raise SystemExit(msg)
    missing = [key for key in _REQUIRED_CONFIG_KEYS if key not in config]
    if missing:
        msg = f"{path}: missing config keys {', '.join(missing)}"
        raise SystemExit(msg)
    model_options = config.get("model_options", {})
    if not isinstance(model_options, dict):
        msg = f"{path}: model_options must be a mapping"
        raise SystemExit(msg)
    filters = config.get("filters", True)
    if not isinstance(filters, bool):
        msg = f"{path}: filters must be a boolean"
        raise SystemExit(msg)
    class_name = config.get("class_name")
    base_model = config.get("base_model")
    spec = str(config["spec"])
    return {
        "source": spec if spec.startswith(_URL_PREFIXES) else str(path.parent / spec),
        "output": path.parent / str(config["output"]),
        "class_name": None if class_name is None else str(class_name),
        "base_model": None if base_model is None else str(base_model),
        "model_options": model_options,
        "filters": filters,
    }


def _base_model_options(value: str) -> dict[str, Any]:
    module, _, name = value.partition(":")
    if not name.isidentifier() or not all(
        part.isidentifier() for part in module.split(".")
    ):
        msg = f"{value!r} is not a 'package.module:Class' path"
        raise SystemExit(msg)
    return {
        "base_class": f"{module}.{name}",
        "use_generic_base_class": False,
        "allow_population_by_field_name": False,
    }


def _class_name(value: str) -> str:
    if (
        not value.isidentifier()
        or keyword.iskeyword(value)
        or value in _RESERVED_MODELS
    ):
        msg = f"{value!r} is not a valid class name"
        raise SystemExit(msg)
    return value


def main(argv: Sequence[str] | None = None) -> None:
    parser = argparse.ArgumentParser(prog="httpxic")
    commands = parser.add_subparsers(dest="command", required=True)
    command = commands.add_parser("generate", help="generate a client from OpenAPI")
    command.add_argument(
        "--config",
        type=Path,
        required=True,
        metavar="FILE",
        help=(
            "JSON or YAML config "
            "(spec, output, class_name, base_model, model_options, filters)"
        ),
    )
    args = parser.parse_args(argv)
    try:
        generate(**_config(args.config))
    except ModuleNotFoundError as exc:
        msg = f"httpxic generate needs the codegen extra: pip install 'httpxic[codegen]' ({exc})"
        raise SystemExit(msg) from exc
