# Generated by httpxic from an OpenAPI spec.
from typing import Annotated

from httpxic import (
    APIClient,
    Body,
    ClientT,
    Header,
    Query,
    delete,
    get,
    post,
    put,
)

from .models import (
    ApiResponse,
    FindPetsByStatusStatus,
    GetInventoryResponse,
    Order,
    Pet,
    User,
)


class PetstoreClient(APIClient[ClientT]):
    @put("/pet")
    def update_pet(self, *, body: Annotated[Pet, Body()]) -> Pet: ...

    @post("/pet")
    def add_pet(self, *, body: Annotated[Pet, Body()]) -> Pet: ...

    @get("/pet/findByStatus")
    def find_pets_by_status(
        self, *, status: Annotated[FindPetsByStatusStatus, Query()]
    ) -> list[Pet]: ...

    @get("/pet/findByTags")
    def find_pets_by_tags(
        self, *, tags: Annotated[list[str], Query()]
    ) -> list[Pet]: ...

    @get("/pet/{pet_id}")
    def get_pet_by_id(self, pet_id: int) -> Pet: ...

    @post("/pet/{pet_id}")
    def update_pet_with_form(
        self,
        pet_id: int,
        *,
        name: Annotated[str | None, Query()] = None,
        status: Annotated[str | None, Query()] = None,
    ) -> Pet: ...

    @delete("/pet/{pet_id}")
    def delete_pet(
        self, pet_id: int, *, api_key: Annotated[str | None, Header()] = None
    ) -> None: ...

    @post(
        "/pet/{pet_id}/uploadImage",
        headers={"Content-Type": "application/octet-stream"},
    )
    def upload_file(
        self,
        pet_id: int,
        *,
        body: Annotated[bytes, Body()],
        additional_metadata: Annotated[
            str | None, Query(alias="additionalMetadata")
        ] = None,
    ) -> ApiResponse: ...

    @get("/store/inventory")
    def get_inventory(self) -> GetInventoryResponse: ...

    @post("/store/order")
    def place_order(self, *, body: Annotated[Order, Body()]) -> Order: ...

    @get("/store/order/{order_id}")
    def get_order_by_id(self, order_id: int) -> Order: ...

    @delete("/store/order/{order_id}")
    def delete_order(self, order_id: int) -> None: ...

    @post("/user")
    def create_user(self, *, body: Annotated[User, Body()]) -> User: ...

    @post("/user/createWithList")
    def create_users_with_list_input(
        self, *, body: Annotated[list[User], Body()]
    ) -> User: ...

    @get("/user/login")
    def login_user(
        self,
        *,
        username: Annotated[str | None, Query()] = None,
        password: Annotated[str | None, Query()] = None,
    ) -> str: ...

    @get("/user/logout")
    def logout_user(self) -> None: ...

    @get("/user/{username}")
    def get_user_by_name(self, username: str) -> User: ...

    @put("/user/{username}")
    def update_user(self, username: str, *, body: Annotated[User, Body()]) -> None: ...

    @delete("/user/{username}")
    def delete_user(self, username: str) -> None: ...
