# Generated by httpxic from an OpenAPI spec.

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, ConfigDict, Field, RootModel
from pydantic import BaseModel as _BaseModel


class BaseModel(_BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class Status(Enum):
    placed = "placed"
    approved = "approved"
    delivered = "delivered"


class Order(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={"xml": {"name": "order"}},
    )
    id: int | None = Field(None, examples=[10])
    pet_id: int | None = Field(None, alias="petId", examples=[198772])
    quantity: int | None = Field(None, examples=[7])
    ship_date: AwareDatetime | None = Field(None, alias="shipDate")
    status: Status | None = Field(
        None, description="Order Status", examples=["approved"]
    )
    complete: bool | None = None


class Category(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={"xml": {"name": "category"}},
    )
    id: int | None = Field(None, examples=[1])
    name: str | None = Field(None, examples=["Dogs"])


class User(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={"xml": {"name": "user"}},
    )
    id: int | None = Field(None, examples=[10])
    username: str | None = Field(None, examples=["theUser"])
    first_name: str | None = Field(None, alias="firstName", examples=["John"])
    last_name: str | None = Field(None, alias="lastName", examples=["James"])
    email: str | None = Field(None, examples=["john@email.com"])
    password: str | None = Field(None, examples=["12345"])
    phone: str | None = Field(None, examples=["12345"])
    user_status: int | None = Field(
        None, alias="userStatus", description="User Status", examples=[1]
    )


class Tag(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={"xml": {"name": "tag"}},
    )
    id: int | None = None
    name: str | None = None


class Status1(Enum):
    available = "available"
    pending = "pending"
    sold = "sold"


class Pet(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={"xml": {"name": "pet"}},
    )
    id: int | None = Field(None, examples=[10])
    name: str = Field(..., examples=["doggie"])
    category: Category | None = None
    photo_urls: list[str] = Field(
        ..., alias="photoUrls", json_schema_extra={"xml": {"wrapped": True}}
    )
    tags: list[Tag] | None = Field(None, json_schema_extra={"xml": {"wrapped": True}})
    status: Status1 | None = Field(None, description="pet status in the store")


class ApiResponse(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={"xml": {"name": "##default"}},
    )
    code: int | None = None
    type: str | None = None
    message: str | None = None


class FindPetsByStatusStatus(Enum):
    available = "available"
    pending = "pending"
    sold = "sold"


class GetInventoryResponse(RootModel[dict[str, int]]):
    root: dict[str, int]
